import express, { Router } from "express";
import { enforceAuth } from "../api.js";
import { router as usersRouter } from "./users.js";
import { router as rolesRouter } from "./roles.js";
import { router as aclsRouter } from "./acls.js";
import { router as configRouter } from "./config.js";
import { permissions } from "../../permissions/permissions.js";
const router: Router = express.Router();
router.get("/permissions", (req, res) => { res.json(permissions); });
router.use(enforceAuth());
router.use("/users", usersRouter);
router.use("/roles", rolesRouter);
router.use("/acls", aclsRouter);
router.use("/roles", rolesRouter);
router.use("/config", configRouter);
export { router };