name: Release

on:
  push:
    tags:
      - "server/v*"
      - "cli/v*"
      - "web/v*"

jobs:
  server-release:
    name: Release Server
    if: startsWith(github.ref, 'refs/tags/server/')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    defaults:
      run:
        working-directory: "./server"
    steps:
      - uses: actions/checkout@v6
      - name: Get Version
        run: echo "VERSION=${GITHUB_REF_NAME#server/}" >> $GITHUB_ENV
      - uses: pnpm/action-setup@v5
        with:
          version: 10
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: "pnpm"
          cache-dependency-path: "server/pnpm-lock.yaml"
      - run: pnpm install --frozen-lockfile
      - name: Lint
        run: pnpm lint
      - name: Compile
        run: pnpm build
      - name: Release
        uses: softprops/action-gh-release@v2
        env:
          VERSION: ${{ env.VERSION }}
        with:
          name: "Server ${{ env.VERSION }}"
  cli-release:
    name: Release CLI
    if: startsWith(github.ref, 'refs/tags/cli/')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      attestations: write
    defaults:
      run:
        working-directory: "./cli"
    steps:
      - uses: actions/checkout@v6
      - name: Get Version
        run: echo "VERSION=${GITHUB_REF_NAME#cli/}" >> $GITHUB_ENV
      - uses: actions/setup-go@v6
        with:
          go-version: stable
          go-version-file: "cli/go.mod"
          cache: true
          cache-dependency-path: "cli/go.sum"
      - run: go mod download
      - name: Vet
        run: go vet ./...
      - name: Build
        env:
          VERSION: ${{ env.VERSION }}
        run: |
          mkdir dist
          GOOS=linux GOARCH=amd64 go build -o dist/folderharbor-cli-${{ env.VERSION }}-linux-amd64 .
          GOOS=linux GOARCH=arm64 go build -o dist/folderharbor-cli-${{ env.VERSION }}-linux-arm64 .
          GOOS=darwin GOARCH=amd64 go build -o dist/folderharbor-cli-${{ env.VERSION }}-macos-amd64 .
          GOOS=darwin GOARCH=arm64 go build -o dist/folderharbor-cli-${{ env.VERSION }}-macos-arm64 .
          GOOS=windows GOARCH=amd64 go build -o dist/folderharbor-cli-${{ env.VERSION }}-windows-amd64.exe .
      - name: Attest Builds
        uses: actions/attest@v4
        with:
          subject-path: 'cli/dist/*'
      - name: Checksums
        run: sha256sum dist/* > dist/checksums.txt
      - name: Release
        uses: softprops/action-gh-release@v2
        env:
          VERSION: ${{ env.VERSION }}
        with:
          name: "CLI ${{ env.VERSION }}"
          files: "cli/dist/**"
  web-release:
    name: Release Web Panel
    if: startsWith(github.ref, 'refs/tags/web/')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      id-token: write
      attestations: write
    defaults:
      run:
        working-directory: "./web"
    steps:
      - uses: actions/checkout@v6
      - name: Get Version
        run: echo "VERSION=${GITHUB_REF_NAME#web/}" >> $GITHUB_ENV
      - uses: pnpm/action-setup@v5
        with:
          version: 10
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: "pnpm"
          cache-dependency-path: "web/pnpm-lock.yaml"
      - run: pnpm install --frozen-lockfile
      - name: Lint
        run: pnpm lint
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          cache-binary: true
      - name: Set up GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        env:
          VERSION: ${{ env.VERSION }}
        with:
          context: .
          push: true
          sbom: true
          provenance: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/${{ github.repository }}/web:latest
            ghcr.io/${{ github.repository }}/web:${{ env.VERSION }}
          build-args: |
            IMAGE_TAG=${{ env.VERSION }}
      - name: Release
        uses: softprops/action-gh-release@v2
        env:
          VERSION: ${{ env.VERSION }}
        with:
          name: "Web ${{ env.VERSION }}"
